sudo: true
os: ubuntu
ubuntu: 
        - 18.04
env:
        - FLASK_CONFIG=staging 
language: node_js
node_js:
        - "11"
        - "10"
before_install:
        - sudo apt-get update
        - yarn cache clean
        - yarn install
script:
        - echo "Hello World"
