sudo: true
os: ubuntu
#haha chris was here!!!!
ubuntu: 
        - 18.04
env:
        - FLASK_CONFIG=staging 
before_install:
        #        - python --versdfddfsdon
        - sudo apt-get update
        - python --version
          #  igggg      - sudo apt-get install python3
          #        - sudo apt-get upgrade python3
matrix:
        include:
                - language: node_js
                  node_js: "11"
                  before_install:
                          - yarn cache clean
                  install:
                          - yarn install
                  script:
                          - echo "Hello chris"      
                                 #yarn cache clean
                                  #- yarn install
                                  # -dfdfsdfsddf lajkdfkdjfnguage: python
                                  #  - language: python
                        - python: "3.7"
                        
                        before_install:
                                - echo "chris"
                        script:
                                - echo "Hello World"
deploy:
provider: linode
local-dir: public
branchs:
        only: 
                - development
