sudo: true
os: ubuntu
#haha chris was here!!!!
ubuntu: 
        - 18.04
env:
        - FLASK_CONFIG=staging 
before_install:
        #        - python --versdfddfsdon
        - sudo apt-get update
          #        - python --version
          #        - sudo apt-get install python3
          #        - sudo apt-get upgrade python3
matrix:
        include:
#               - language: node_js
#                 node_js: "11"
#                 before_install:
#                         - yarn cache clean
#                 install:
#                         - yarn install
#                 script:
#                         - echo "Hello chris"      
                                 #yarn cache clean
                                  #- yarn install
                - language: python
                  python: "3.7"
                  dist: "xenial"
                  sudo: true
                  install:
                        - pip install -r api/requirements.txt
                  script:
                        - echo "Hello World"
# reset database script (david) 
# run server side testing script (pytest)
# create script by configuration and make file
# install nginx??
# install postgress and configure it
notifications:       
        slack: tumissionscomputing:wp25PPGEFitgDVKamhxxq6jU
deploy:
provider: linode
local-dir: public
branchs:
        only: 
                - development
