sudo: true
os: ubuntu
#haha chris was here!!!!
ubuntu: 
        - 18.04
env:
        - FLASK_CONFIG=staging 
language: node_js
node_js:
        - "11"
        - "10"
before_install:
        - sudo apt-get update
        - yarn cache clean
        - yarn install
script:
        - echo "Hello World"
deploy:
        provider: linode
        local-dir: public
                only: 
                        - corpus-cristi/development
