sudo: true
os: ubuntu
ubuntu: 
        - 18.04
env:
        - FLASK_CONFIG=staging 
before_install:
        - sudo apt-get update
matrix:
        include:
                - language: node_js
                  node_js: "11"
                  before_install:
                          - yarn cache clean
                  install:
                          - yarn install
                  script:
                          - echo "Done with Node_js"  
                - language: python
                  python: "3.7"
                  dist: "xenial"
                  sudo: true
                  env: 
                        - FLASK_APP=cc-api.py
                  install:
                        - pip install -r api/requirements.txt
                          # - pip install -U pytest
                        - ls
                          #- cd api/
                        - sudo apt install postgresql
                        - sudo apt install nginx
                  script:
                        - sudo service postgresql start
                        - sudo -u postgres psql createuser -w arco
                        - sudo -u postgres psql createdb -O arco cc-staging 
                        - flask db upgrade
                        - flask data load-all
                        - rm migrations/versions/*.py
                        - sudo nginx -t
                        - sudo systemctl restart nginx
                        - cd ../
                          # - pytest

script:
        - 
# create script by configuration and make file
# fix flask data load-al112
notifications:       
        slack: tumissionscomputing:wp25PPGEFitgDVKamhxxq6jU
deploy:
provider: linode
local-dir: public
branchs:
        only: 
                - development
