sudo: true
os: ubuntu
#haha chris was here!!!!
ubuntu: 
        - 18.04
env:
        - FLASK_CONFIG=staging 
before_install:
        - sudo apt-get update
matrix:
        include:
                 - language: node_js
                        node_js:
                                - "11"
                                  # before_install:
                                #- yarn cache clean
                                  #- yarn install
                                  # - language: python
                  # python:
                          #                          - "3.7"


script:
        - echo "Hello World"
deploy:
provider: linode
local-dir: public
branchs:
        only: 
                - development
